---
- name: Install required packages
  dnf:
    name:
      - git
      - python39
  become: yes

- name: Create albs user
  ansible.builtin.user:
    name: "{{ albs_user }}"
    create_home: yes
    groups: ["docker", "wheel"]

- name: Add paswordless sudo for albs user
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'

- name: Add ssh key to albs user
  ansible.posix.authorized_key:
    key: "{{ albs_ssh_key }}"
    user: "{{ albs_user }}"

- name: Add IP address of all hosts to all hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item }}$'
    line: "{{ hostvars[item].ansible_host }} {{item}}"
    state: present
  when: hostvars[item].ansible_host is defined
  with_items: "{{ groups.all }}"
