---
- name: Clone frontend sources for https
  git:
    repo: "{{ git_protocol }}://github.com/AlmaLinux/albs-frontend.git"
    dest: "{{ sources_root }}/albs-frontend"
    clone: yes
    update: yes
    force: yes
    version: "{{ albs_frontend }}"
  when: git_protocol == 'https'

- name: Clone frontend sources for ssh
  git:
    repo: "git@github.com:AlmaLinux/albs-frontend.git"
    dest: "{{ sources_root }}/albs-frontend"
    clone: yes
    update: yes
    force: yes
  when: git_protocol == 'ssh'

