---
- name: Add Docker CE repository
  copy:
    src: docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
    owner: root
    group: root
    mode: 0644
  become: yes

- name: Install Docker CE
  dnf:
    name:
      - containerd.io
      - docker-ce
      - docker-ce-cli
  become: yes

- name: Enable and start Docker daemon
  service:
    name: docker
    enabled: true
    state: started
  become: yes